name: Framed by TERRE
favicon: null
layout_spectrum: 0.08097713300958276
typography_spectrum: 0.7097943271510303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.07173004210926592
  lightness: 0.6700227716937661
  saturation: 0.17535486002452672
  rhythmicContrast: 0.4305351125076413
purpose: []
